import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {Presentation,PresentationFile,FileBlob} from '@oai/artifact-tool';
import {createCanvas,GlobalFonts} from '@napi-rs/canvas';
const BUILD=path.dirname(fileURLToPath(import.meta.url)),WORK=path.dirname(BUILD),SAMPLE=process.argv.includes('--sample'),MODE=SAMPLE?'sample':'final',OUT=path.join(WORK,SAMPLE?'sample':'output');
const AUDIT=path.join(path.dirname(WORK),'execution/pipeline_post_robustness_audit_20260929_1448');
const SKILL='C:/Users/17703/.codex/plugins/cache/openai-primary-runtime/presentations/26.927.11222/skills/presentations',PYTHON='C:/Users/17703/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const {finalizePresentation}=await import(pathToFileURL(path.join(SKILL,'container_tools/artifact_tool_utils.mjs')).href);
const ROOT_SHA='f55b05559de3ca536170de4ea0be79988dd7c5cf0c822be5f3572eb31a57af0a',CAP_SHA='473d5fba90c3fc0d044733ffb19e1f2955f08df96f89d4c643ad54d6ff15ca09',T5_SHA='033b6eaea71b3084ca043902f6ba03b6487bf1762a9180963357103097d172cc';
const W=181.9*72/25.4,H=467,S=4/3,HEIGHT_MM=H*25.4/72,COLORS={visual:'#0072B2',full:'#D55E00'},COVERAGES=[.5,.75,.9,1];
const ALL_TASKS=['university1652_drone_to_satellite','university1652_satellite_to_drone','university1652_street_to_satellite',...[150,200,250,300].flatMap(h=>[`sues200_uav_${h}m_to_satellite`,`sues200_satellite_to_uav_${h}m`])],TASKS=SAMPLE?['university1652_drone_to_satellite','sues200_satellite_to_uav_150m']:ALL_TASKS;
let checks=0;const check=(v,m)=>{checks++;if(!v)throw new Error(m);};
const hash=b=>createHash('sha256').update(b).digest('hex'),norm=p=>path.normalize(p).toLowerCase(),inputs=[];
const describe=async p=>{const b=await fs.readFile(p);return {path:p,sha256:hash(b),bytes:b.length};},create=async(p,b)=>fs.writeFile(p,b,{flag:'wx'});
async function bind(p,d){const b=await fs.readFile(p);check(hash(b)===d.sha256&&(d.bytes===undefined||d.bytes===b.length),'SHA/size '+p);inputs.push({path:p,sha256:hash(b),bytes:b.length});return b;}
const rootPath=path.join(AUDIT,'ROOT_POST_ROBUSTNESS_ADOPTION.json'),rootBytes=await bind(rootPath,{sha256:ROOT_SHA}),root=JSON.parse(rootBytes);check(root.accepted_with_stated_limits===true,'Accepted numerical-source root');
const rootMap=new Map(root.bindings.map(d=>[norm(d.path),d])),capturePath=path.join(AUDIT,'a1/CAPTURE.json');check(rootMap.get(norm(capturePath)).sha256===CAP_SHA,'Root binds capture');
const captureBytes=await bind(capturePath,rootMap.get(norm(capturePath))),capture=JSON.parse(captureBytes),sourcePath=path.join(AUDIT,'a1/query/transactions_t5_selective_calibration.json'),binding=rootMap.get(norm(sourcePath));
check(binding&&binding.sha256===T5_SHA&&binding.bytes===744943,'Exact source snapshot');const cb=capture.bindings.filter(d=>norm(d.snapshot)===norm(sourcePath));check(cb.length===1&&cb[0].sha256===T5_SHA&&cb[0].bytes===744943,'Unique capture snapshot');
const sourceBytes=await bind(sourcePath,binding),t5=JSON.parse(sourceBytes);await create(path.join(OUT,'source_data/transactions_t5_selective_calibration.json'),sourceBytes);await create(path.join(OUT,'provenance/ROOT_POST_ROBUSTNESS_ADOPTION.json'),rootBytes);await create(path.join(OUT,'provenance/CAPTURE.json'),captureBytes);
for(const name of ['README.md','REVIEW.json']){const p=path.join(AUDIT,name),b=await fs.readFile(p),d=rootMap.get(norm(p));if(d)check(hash(b)===d.sha256&&b.length===d.bytes,'Root-bound contextual report');inputs.push({path:p,sha256:hash(b),bytes:b.length,role:'Contextual upstream report',rootBound:!!d});await create(path.join(OUT,'provenance',`UPSTREAM_${name}`),b);}
check(t5.status==='completed'&&t5.unit==='fraction'&&t5.schema_version==='lgm-game.transactions-t5-selective-calibration.v1','Completed T5 schema');
check(t5.native_rows.length===66&&t5.paired_comparisons.length===132&&t5.registered_comparison_count===132,'66 native N sources and132 paired rows');
check(new Set(t5.paired_comparisons.map(r=>`${r.task}/${r.seed}/${r.requested_coverage}`)).size===132,'Unique paired keys');
check([...new Set(t5.paired_comparisons.map(r=>r.requested_coverage))].sort((a,b)=>a-b).join(',')===COVERAGES.join(','),'Actual requested coverage50/75/90/100');
const flat=[];
for(const task of ALL_TASKS)for(const seed of [1,2,3]){
 const nv=t5.native_rows.filter(r=>r.task===task&&r.seed===seed&&r.variant==='visual'),nf=t5.native_rows.filter(r=>r.task===task&&r.seed===seed&&r.variant==='full');check(nv.length===1&&nf.length===1,'Native N record identity');
 const N=nv[0].risk_coverage.queries;check(Number.isInteger(N)&&N>0&&nf[0].risk_coverage.queries===N&&nv[0].query_membership_sha256===nf[0].query_membership_sha256,'Same saved full query N and membership descriptor');
 for(const requested of COVERAGES){const matches=t5.paired_comparisons.filter(r=>r.task===task&&r.seed===seed&&r.requested_coverage===requested);check(matches.length===1,'Each registered paired row');const r=matches[0],s=r.coverage_constrained_success,k=r.selected_queries_per_variant;
  check(s.definition==='selected AND top1-correct over the common full query set','Saved success denominator definition');check(Number.isInteger(k)&&k===Math.ceil(requested*N)&&k>0&&k<=N,'Saved selected k and ceil coverage');check(r.realized_coverage===k/N,'Saved realized coverage');
  check(Number.isInteger(r.visual_full_selected_query_overlap)&&r.visual_full_selected_query_overlap>=0&&r.visual_full_selected_query_overlap<=k,'Saved set overlap range');
  for(const variant of ['visual','full'])check(Number.isFinite(s[`${variant}_rate`])&&s[`${variant}_rate`]>=0&&s[`${variant}_rate`]<=r.realized_coverage+1e-14,'Saved success fraction range');
  if(requested===1)check(k===N&&r.visual_full_selected_query_overlap===N,'Preserve complete coverage endpoint');
  flat.push({dataset:r.dataset,task,seed,full_query_N:N,requested_coverage:requested,realized_coverage:r.realized_coverage,selected_queries_per_variant:k,visual_full_selected_query_overlap:r.visual_full_selected_query_overlap,visual_success_rate:s.visual_rate,full_success_rate:s.full_rate,visual_success_percent:s.visual_rate*100,full_success_percent:s.full_rate*100,realized_coverage_percent:r.realized_coverage*100,full_query_membership_sha256:nv[0].query_membership_sha256,source_json_sha256:T5_SHA});
 }
}
check(flat.length===132,'All132 paired display rows');
const headers=Object.keys(flat[0]);function csv(rows){return headers.join(',')+'\n'+rows.map(r=>headers.map(k=>String(r[k])).join(',')).join('\n')+'\n';}
await create(path.join(OUT,'source_data/PAIRED_SUCCESS_132.csv'),csv(flat));const pageCSVs=new Map();for(const task of TASKS){const b=csv(flat.filter(r=>r.task===task));pageCSVs.set(task,b);await create(path.join(OUT,'source_data',`t5_${task}__paired_success.csv`),b);}
const provenance=path.join(WORK,SAMPLE?'INPUT_PROVENANCE_SAMPLE.json':'INPUT_PROVENANCE.json');await create(provenance,JSON.stringify({schema:'native-t5-paired-input-provenance.v1',mode:MODE,rootSha256:ROOT_SHA,inputs,allPairedRows:132,requestedCoverages:COVERAGES,plottedTasks:TASKS,plottedRows:TASKS.length*12,plottedPanels:TASKS.length*3,plottedPoints:TASKS.length*24,derivedCSV:'Direct paired success fields and×100 only; N from exact matching native records. No query success, overlap, selective accuracy, inference or science recomputation.',copies:await Promise.all((await fs.readdir(path.join(OUT,'source_data'))).map(n=>describe(path.join(OUT,'source_data',n))))},null,2));
check(GlobalFonts.families.some(f=>f.family==='Arial'),'Arial available');const ctx=createCanvas(1,1).getContext('2d'),escape=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function label(task){if(task.startsWith('university1652_'))return 'University-1652: '+({'drone_to_satellite':'Drone → satellite','satellite_to_drone':'Satellite → drone','street_to_satellite':'Street → satellite'}[task.replace('university1652_','')]);let m=task.match(/^sues200_uav_(\d+)m_to_satellite$/);if(m)return `SUES-200: UAV ${m[1]} m → satellite`;m=task.match(/^sues200_satellite_to_uav_(\d+)m$/);check(m,'Registered SUES task');return `SUES-200: Satellite → UAV ${m[1]} m`;}
const pres=Presentation.create({slideSize:{width:W*S,height:H*S}}),figures=[];
for(let ti=0;ti<TASKS.length;ti++){
 const task=TASKS[ti],rows=flat.filter(r=>r.task===task),slide=pres.slides.add();slide.background.fill='#FFFFFF';const primitives=[],panels=[];
 const add=(tag,id,a)=>primitives.push({tag,id,...a}),text=(id,x,y,content,size=8,bold=false,anchor='start',fill='#222222')=>add('text',id,{x,y,text:content,fontSize:size,bold,anchor,fill}),line=(id,x1,y1,x2,y2,stroke='#444444',width=.6)=>add('line',id,{x1,y1,x2,y2,stroke,width}),marker=(id,x,y,variant)=>add(variant==='visual'?'circle':'rect',id,{x,y,r:variant==='visual'?2.35:1.9,fill:variant==='visual'?'#FFFFFF':'none',stroke:COLORS[variant],width:.9});
 text('title',15,18,label(task),10,true);text('subtitle',15,34,'Coverage-constrained success on the full query set',9,true);marker('legend/visual/marker',18,48,'visual');text('legend/visual/text',27,51,'Visual (V)',8);marker('legend/full/marker',110,48,'full');text('legend/full/text',119,51,'Full (F)',8);
 text('y-axis-label',15,70,'Selected AND Top-1 correct / full query N (%)',8);
 for(const seed of [1,2,3]){
  const id=`${task}/seed-${seed}`,x=42+(seed-1)*158,y=99,pw=126,ph=128,bottom=y+ph,srows=rows.filter(r=>r.seed===seed),N=srows[0].full_query_N;
  text(`${id}/heading`,x+pw/2,86,`Seed ${seed}`,9,true,'middle');
  for(const v of [0,25,50,75,100]){const yy=bottom-v/100*ph;line(`${id}/y-grid-${v}`,x,yy,x+pw,yy,'#E0E6EC',.45);text(`${id}/y-label-${v}`,x-5,yy+2.7,String(v),8,false,'end');const xx=x+v/100*pw;line(`${id}/x-tick-${v}`,xx,bottom,xx,bottom+3);text(`${id}/x-label-${v}`,xx,bottom+14,String(v),8,false,'middle');}
  line(`${id}/y-axis`,x,y,x,bottom);line(`${id}/x-axis`,x,bottom,x+pw,bottom);const series=[];
  for(const variant of ['visual','full']){const points=srows.map(r=>({...r,variant,success_rate:r[`${variant}_success_rate`],x:x+r.realized_coverage*pw,y:bottom-r[`${variant}_success_rate`]*ph}));for(let i=1;i<points.length;i++)line(`${id}/${variant}/guide-${i}-${i+1}`,points[i-1].x,points[i-1].y,points[i].x,points[i].y,COLORS[variant],.9);for(const p of points)marker(`${id}/${variant}/point-cov-${p.requested_coverage}`,p.x,p.y,variant);series.push({variant,points});}
  text(`${id}/count/N`,x+pw/2,283,`Full query N = ${N.toLocaleString('en-US')}`,8,true,'middle');text(`${id}/count/header/requested`,x+7,300,'Req%',8,true,'middle');text(`${id}/count/header/kN`,x+61,300,'Actual k / N',8,true,'middle');text(`${id}/count/header/overlap`,x+111,300,'Overlap',8,true,'middle');line(`${id}/count/header/rule`,x-6,305,x+pw+5,305,'#CAD2DA',.5);
  for(const [i,r] of srows.entries()){const yy=316+i*14; text(`${id}/count/cov-${r.requested_coverage}/requested`,x+7,yy,String(r.requested_coverage*100),8,false,'middle');text(`${id}/count/cov-${r.requested_coverage}/kN`,x+61,yy,`${r.selected_queries_per_variant}/${N}`,8,false,'middle');text(`${id}/count/cov-${r.requested_coverage}/overlap`,x+111,yy,String(r.visual_full_selected_query_overlap),8,false,'middle');}
  panels.push({seed,queries:N,plot:{x,y,width:pw,height:ph},xRange:[0,100],yRange:[0,100],rows:srows,series});
 }
 text('x-axis-label',W/2,260,'Realized selected coverage = k / N (%)',8,false,'middle');
 const footnotes=[
  'Success uses all N queries as denominator, not accuracy among the selected k.',
  'Variants select their own queries by margin; equal k does not mean equal members.',
  'Overlap counts shared selected members, not shared correct predictions.',
  'Four saved coverage points only; connecting lines guide the eye. No added origin.',
  'Higher coverage admits more queries; rising success need not mean better ranking.',
  'Seeds/tasks stay separate. No pooled statistics, SD, CI, bootstrap or p-values shown.'
 ];footnotes.forEach((t,i)=>text(`footnote-${i+1}`,15,384+i*13,t,8));
 for(const p of primitives){const name=`${task}/${p.id}`;if(p.tag==='text'){ctx.font=`${p.bold?'bold':'normal'} ${p.fontSize*S}px Arial`;const tw=ctx.measureText(p.text).width+1,left=p.x*S-(p.anchor==='middle'?tw/2:p.anchor==='end'?tw:0);check(left>=0&&left+tw<=W*S,'Text horizontal page fit');check(p.y-p.fontSize>=0&&p.y+3<=H,'Text vertical page fit');const sh=slide.shapes.add({geometry:'textbox',name,position:{left,top:(p.y-p.fontSize*.92)*S,width:tw,height:p.fontSize*S*1.25},fill:'none',line:{fill:'none',width:0}});sh.text=p.text;sh.text.style={typeface:'Arial',fontSize:p.fontSize*S,bold:p.bold,color:p.fill,alignment:p.anchor==='middle'?'center':p.anchor==='end'?'right':'left',verticalAlignment:'top',autoFit:'none',wrap:'none',insets:{top:0,bottom:0,left:0,right:0}};}
  else if(p.tag==='line')slide.shapes.add({geometry:'line',name,position:{left:Math.min(p.x1,p.x2)*S,top:Math.min(p.y1,p.y2)*S,width:Math.abs(p.x2-p.x1)*S,height:Math.abs(p.y2-p.y1)*S,verticalFlip:(p.x2-p.x1)*(p.y2-p.y1)<0},fill:'none',line:{fill:p.stroke,width:p.width*S}});
  else slide.shapes.add({geometry:p.tag==='circle'?'ellipse':'rect',name,position:{left:(p.x-p.r)*S,top:(p.y-p.r)*S,width:p.r*2*S,height:p.r*2*S},fill:p.fill,line:{fill:p.stroke,width:p.width*S}});
 }
 const svg=[`<svg xmlns="http://www.w3.org/2000/svg" width="181.9mm" height="${HEIGHT_MM}mm" viewBox="0 0 ${W} ${H}">`,`<title>${escape(label(task)+': coverage-constrained success')}</title>`,`<desc>Three separate seeds, four stored coverage observations per variant. Success means selected AND correct over full common N. Equal selected counts do not imply equal membership. No added origin, inference or pooling.</desc>`,`<rect id="background" x="0" y="0" width="${W}" height="${H}" fill="white"/>`];
 for(const p of primitives){const id=`id="${escape(p.id)}"`;if(p.tag==='text')svg.push(`<text ${id} x="${p.x}" y="${p.y}" font-family="Arial" font-size="${p.fontSize}" font-weight="${p.bold?'bold':'normal'}" text-anchor="${p.anchor}" fill="${p.fill}">${escape(p.text)}</text>`);else if(p.tag==='line')svg.push(`<line ${id} x1="${p.x1}" y1="${p.y1}" x2="${p.x2}" y2="${p.y2}" stroke="${p.stroke}" stroke-width="${p.width}"/>`);else if(p.tag==='circle')svg.push(`<circle ${id} cx="${p.x}" cy="${p.y}" r="${p.r}" fill="${p.fill}" stroke="${p.stroke}" stroke-width="${p.width}"/>`);else svg.push(`<rect ${id} x="${p.x-p.r}" y="${p.y-p.r}" width="${p.r*2}" height="${p.r*2}" fill="${p.fill}" stroke="${p.stroke}" stroke-width="${p.width}"/>`);}
 svg.push('</svg>');const svgPath=path.join(OUT,'native_svg',`t5_paired_${task}.svg`);await create(svgPath,svg.join('\n')+'\n');
 const caption=`${label(task)}. Coverage-constrained success is the saved count of queries selected AND Top-1 correct, divided by the common full query N, not the selected-subset accuracy whose denominator is k. The y coordinate copies coverage_constrained_success.visual_rate/full_rate×100. The x coordinate copies the saved realized_coverage=k/N×100. Each variant has four observations, at requested coverage50%,75%,90%,100%; actual realized coverage may differ after k=ceil(requested×N). The 75% observation is the paired source row, not an interpolation of native ten-point coverage results. Full query N and its shared membership descriptor are taken from the exact corresponding Visual/Full native records. Each variant ranks its own raw cosine Top-1 minus Top-2 margins with stable query-order ties and selects k queries. The same k is not proof of identical selected members. The four-row table reports requested coverage, exact k/N per variant and the saved count of shared selected members (overlap), which is not the number jointly correct. At100% coverage, k=overlap=N, and success is the full-query R@1; all endpoints are retained. Lines connect only adjacent saved observations as visual guides, with no additional origin, extrapolation, interpolation claim or area/integral metric. Increasing coverage admits more queries and can mechanically increase full-N success; it does not by itself establish improved ranking performance. True point coordinates are retained, including overlap, without jitter. Tasks, directions, heights and the three seeds stay separate. No selective-accuracy difference, SD, confidence interval, bootstrap interval, p-value, Holm decision or significance is plotted or recalculated. The full source JSON retains all132 original paired rows and inferential fields, but this figure does not add inference or claim their recomputation. Saved success/selection/overlap fields are copied directly; no query arrays or statistics are reconstructed. These are official clean-query results. Upstream typed-scalar query validation, inherited checkpoint/cache/image SHA authority and historical metadata-chain gaps remain unchanged. No NPZ, weight, cache, image, model, full-ranking or all-positive-rank AP is read or recomputed, and this graphical conversion creates no new scientific run or T6 completion.`;
 slide.speakerNotes.textFrame.setText(`${caption}\n\nRoot adoption SHA256: ${ROOT_SHA}\nExact original T5 JSON SHA256: ${T5_SHA}\n\nAll12 paired display rows for this task, saved precision retained; N sources are same-task/seed native records:\n${pageCSVs.get(task)}`);
 figures.push({ordinal:ti+1,task,title:label(task),widthMm:181.9,heightMm:HEIGHT_MM,widthPt:W,heightPt:H,minFontPt:8,pairedRows:12,points:24,guides:18,panels,primitives,caption,svg:await describe(svgPath),sourceCSV:await describe(path.join(OUT,'source_data',`t5_${task}__paired_success.csv`))});
}
const candidate=path.join(BUILD,`t5_paired_${MODE}.candidate.pptx`),final=path.join(OUT,`t5_paired_native_editable_${TASKS.length}figures.pptx`),receipt=path.join(BUILD,`${MODE}.validation.json`);await(await PresentationFile.exportPptx(pres)).save(candidate);
await finalizePresentation({workspaceDir:WORK,candidatePath:candidate,finalPath:final,explicitTotalSlideCount:TASKS.length,requiredNativeTableOwnerSlides:[],requiredNativeChartOwnerSlides:[],pythonExecutable:PYTHON,integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu',`${Math.round(181.9*36000)},${Math.round(HEIGHT_MM*36000)}`,'--cover-role','none',...TASKS.flatMap((_,i)=>['--approved-dense-slide',String(i+1)])],fontPolicy:{basis:'design',families:['Arial']},verifyArtifactToolImport:true,receiptPath:receipt});
const imported=await PresentationFile.importPptx(await FileBlob.load(final));for(let i=0;i<TASKS.length;i++){const fig=figures[i],png=path.join(OUT,'previews',`${String(i+1).padStart(2,'0')}_t5_paired_${fig.task}.png`);await create(png,new Uint8Array(await(await imported.export({slide:imported.slides.items[i],format:'png',scale:2})).arrayBuffer()));fig.preview=await describe(png);console.log(JSON.stringify({page:i+1,task:fig.task,preview:png}));}
await create(path.join(WORK,SAMPLE?'BUILD_REPORT_SAMPLE.json':'BUILD_REPORT.json'),JSON.stringify({schema:'native-t5-paired-build.v1',mode:MODE,utc:new Date().toISOString(),source:await describe(fileURLToPath(import.meta.url)),inputProvenance:await describe(provenance),checks,figureCount:TASKS.length,pairedRows:TASKS.length*12,points:TASKS.length*24,guides:TASKS.length*18,panels:TASKS.length*3,requestedCoverages:COVERAGES,pptx:await describe(final),receipt:await describe(receipt),figures,scientificExecution:false,PowerPointOpened:false,rendering:'Every finalPPTX page imported and CPU rendered using artifact-tool',limits:['Native individual objects, not grouped charts or embedded images.','No selection/success/overlap statistics or NPZ/model/scientific recomputation.','Producer, independent and root reviews remain distinct.']},null,2));console.log(JSON.stringify({complete:true,mode:MODE,checks,figures:TASKS.length}));
