"""Inspect this project's own checkpoint before restarting any training process."""
import os
for key in ('OPENBLAS_NUM_THREADS','OMP_NUM_THREADS','MKL_NUM_THREADS'):
    os.environ[key]='1'
import datetime, hashlib, json, zipfile
from pathlib import Path
import torch
torch.set_num_threads(1)
root=Path(__file__).resolve().parent/'memory_recovery_20260914_1300'
run=root/'run'
history=json.loads((run/'history.json').read_text(encoding='utf-8'))
manifest=json.loads((run/'run_manifest.json').read_text(encoding='utf-8'))
reports=[]
for name in ('last.pt','best.pt'):
    path=run/name
    with zipfile.ZipFile(path) as z:
        assert z.testzip() is None
    # Trusted checkpoint generated by this local frozen training run; it contains
    # Python and NumPy RNG states required for continuation, not just weights.
    state=torch.load(path,map_location='cpu',weights_only=False,mmap=True)
    required={'model_state','optimizer_state','scheduler_state','scaler_state','rng_state','immutable_config','run_config_sha256','history','epoch'}
    assert required <= state.keys()
    assert state['epoch']==66==manifest['last_completed_epoch']
    assert len(history)==67 and state['history']==history
    assert state['run_config_sha256']==manifest['run_config_sha256']
    assert {'python','numpy','torch_cpu','torch_cuda'} <= state['rng_state'].keys()
    assert len(state['rng_state']['torch_cuda'])==1
    tensor_count=0
    def check(value):
        global tensor_count
        if isinstance(value,torch.Tensor):
            tensor_count+=1
            if value.is_floating_point(): assert bool(torch.isfinite(value).all())
        elif isinstance(value,dict):
            for item in value.values(): check(item)
        elif isinstance(value,(tuple,list)):
            for item in value: check(item)
    check(state['model_state']);check(state['optimizer_state'])
    assert len(state['optimizer_state']['state'])>0
    reports.append({'file':str(path),'sha256':hashlib.file_digest(path.open('rb'),'sha256').hexdigest(),'epoch_zero_based':state['epoch'],'completed_epochs':len(history),'finite_model_and_optimizer_tensors':tensor_count,'optimizer_parameter_states':len(state['optimizer_state']['state']),'scaler_state':state['scaler_state'],'scheduler_state':state['scheduler_state'],'config_sha256':state['run_config_sha256'],'rng_state_fields':list(state['rng_state'])})
    del state
report={'status':'verified_complete_epoch_67','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'torch':torch.__version__,'cuda_initialized':torch.cuda.is_initialized(),'reports':reports,'note':'Read only audit before main restart. No auxiliary scientific imports are permitted during resumed training.'}
assert not report['cuda_initialized']
(root/'checkpoint_verification.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'status':report['status'],'cuda_initialized':False,'files':len(reports)}))
