$ErrorActionPreference='Stop'
$base='C:\OneDrive\文档\LGM-GAME\outputs\paper_evidence_rebuild_20260914\transfer_native_figures_20260929_1750'
$out=Join-Path $base 'output'
$review=$PSScriptRoot
$rootPath=Join-Path $base 'ROOT_TRANSFER_NATIVE_ADOPTION.json'
$root=Get-Content -LiteralPath $rootPath -Raw|ConvertFrom-Json
$ix=Get-Content -LiteralPath (Join-Path $out 'FIGURE_INDEX.json') -Raw|ConvertFrom-Json
$paths=@($rootPath,(Join-Path $out 'README.md'),(Join-Path $out 'CAPTIONS.md'),(Join-Path $out 'FIGURE_INDEX.json'),(Join-Path $out 'source_data\THREE_SEED_SUMMARY.csv'),(Join-Path $out 'source_data\SEED_RESULTS.csv'),(Join-Path $out 'source_data\FULL_MINUS_VISUAL.csv'),(Join-Path $out 'provenance\ROOT_AGGREGATION_ADOPTION.json'),(Join-Path $out 'native_svg\transfer_university_to_sues.svg'),(Join-Path $out 'native_svg\transfer_sues_to_university.svg'),(Join-Path $out 'transfer_university_to_sues_native_editable.pptx'),(Join-Path $out 'transfer_sues_to_university_native_editable.pptx'),'C:\OneDrive\文档\LGM-GAME\outputs\paper_evidence_rebuild_20260914\execution\HANDOFF.md')
$bindings=@(); foreach($p in $paths){$file=Get-Item -LiteralPath $p; $hash=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant(); $expected=@($root.bindings|Where-Object {$_.path -eq $p}|Select-Object -First 1);$bound=$expected.Count -gt 0;if($bound -and ($hash -ne $expected[0].sha256 -or $file.Length -ne $expected[0].bytes)){throw ('Source adoption mismatch: '+$p)};$bindings+=([ordered]@{path=$p;bytes=$file.Length;sha256=$hash;matches_selected_root_binding=if($bound){$true}else{$null};scope=if($bound){'Selected original binding only'}else{'Observed review input; no prior binding claimed'}})}
Add-Type -AssemblyName System.IO.Compression.FileSystem
$figs=@();foreach($fig in $ix.figures){[xml]$svg=Get-Content -LiteralPath (Join-Path $out $fig.svg) -Raw;$texts=@($svg.SelectNodes('//*[local-name()="text"]')|ForEach-Object {$_.InnerText});$missing=@($fig.values|Where-Object {$texts -notcontains $_.valueText});if($missing.Count){throw 'Original SVG value-label mismatch'};$z=[IO.Compression.ZipFile]::OpenRead((Join-Path $out $fig.pptx));try{$e=$z.GetEntry('ppt/notesSlides/notesSlide1.xml');$ms=[IO.MemoryStream]::new();$s=$e.Open();try{$s.CopyTo($ms)}finally{$s.Dispose()};$bytes=$ms.ToArray();$ms.Dispose();[xml]$noteXml=[Text.Encoding]::UTF8.GetString($bytes);$note=($noteXml.SelectNodes('//*[local-name()="t"]')|ForEach-Object {$_.InnerText})-join "`n";$noteHash=([BitConverter]::ToString([Security.Cryptography.SHA256]::HashData($bytes))).Replace('-','').ToLowerInvariant();$np=Join-Path $review ($fig.id+'_original_notes.txt');if(Test-Path -LiteralPath $np){throw ('Output already exists: '+$np)};[IO.File]::WriteAllText($np,$note,[Text.UTF8Encoding]::new($false));$csvchecks=@();foreach($n in @('THREE_SEED_SUMMARY.csv','SEED_RESULTS.csv')){$csv=Get-Content -LiteralPath (Join-Path $out ('source_data\'+$n)) -Raw;$present=$note.Replace("`r`n","`n").Contains($csv.Replace("`r`n","`n").TrimEnd("`n"));if(-not $present){throw ('Notes do not contain original CSV text: '+$n)};$csvchecks+=([ordered]@{csv=$n;exact_text_except_line_ending_and_terminal_newline_present=$present})};$captionPresent=$note.Contains($fig.caption);if(-not $captionPresent){throw 'Caption not in original notes'};$figs+=([ordered]@{id=$fig.id;title=$fig.title;tasks=$fig.tasks;axes=$fig.axes;summary_groups=$fig.summaryGroups;metric_summaries=$fig.metricSummaries;original_svg_all_saved_value_texts_present=$true;value_labels_checked=$fig.values.Count;low_street_labels=@($fig.values|Where-Object {$_.task -match 'street'}|Select-Object variant,metric,valueText,meanFraction,sampleSdFraction);notes_xml_entry=$e.FullName;notes_xml_sha256=$noteHash;notes_text_sidecar=$np;caption_exact_text_present=$captionPresent;csv_notes_checks=$csvchecks})}finally{$z.Dispose()}}
$deltas=Import-Csv -LiteralPath (Join-Path $out 'source_data\FULL_MINUS_VISUAL.csv')
$signs=[ordered]@{rows=$deltas.Count;r_at_1_saved_mean_delta_negative=@($deltas|Where-Object {[double]$_.r_at_1_mean_delta -lt 0}).Count;map_saved_mean_delta_negative=@($deltas|Where-Object {[double]$_.official_trapezoid_mAP_mean_delta -lt 0}).Count;mrr_saved_mean_delta_negative=@($deltas|Where-Object {[double]$_.MRR_mean_delta -lt 0}).Count;street_saved_deltas=@($deltas|Where-Object {$_.task -match 'street'}|Select-Object source_dataset,target_dataset,task,r_at_1_mean_delta_x100,official_trapezoid_mAP_mean_delta_x100,MRR_mean_delta_x100);scope='Sign/count comparison of saved delta fields only; no statistics rebuilt.'}
$report=[ordered]@{schema='independent-static-t3-visio-semantics.v1';created_utc=[DateTime]::UtcNow.ToString('o');accepted_original_source_scope=$root.accepted;source_scope=$root.scope;figures=$figs;saved_delta_sign_checks=$signs;review_type='Static semantics and selected small-source integrity only';new_visio_artifacts_reviewed=$false;producer_document_review='Pending new artifacts';limits=@('No new means, SD, CI, bootstrap, significance or scientific aggregation computed.','No model, weights, NPZ, cache, image, fullranking or AP computation.','No COM, application launch, GPU, science libraries, old suites or live-state changes.','No geometry or rendered visual review performed; original source numeric labels and notes text only.','Existing checkpoint/cache/image SHA and historical provenance gaps remain.','Only selected source bindings checked; root adoption not expanded into all historical dependencies.')}
$manifest=[ordered]@{schema='independent-t3-semantics-selected-sources.v1';created_utc=$report.created_utc;files=$bindings;file_count=$bindings.Count;root_bound_selected_count=@($bindings|Where-Object {$_.matches_selected_root_binding -eq $true}).Count;notes='Only these small files and PPT notes were read/hashed; no original weights/cache/NPZ/images or full historical suite read.'}
foreach($pair in @(@('STATIC_SEMANTICS.json',$report),@('SOURCE_SHA_MANIFEST.json',$manifest))){$dest=Join-Path $review $pair[0];if(Test-Path -LiteralPath $dest){throw ('Output already exists: '+$dest)};[IO.File]::WriteAllText($dest,($pair[1]|ConvertTo-Json -Depth 15),[Text.UTF8Encoding]::new($false))}
[ordered]@{sources=$bindings.Count;root_bound_sources=$manifest.root_bound_selected_count;source_value_labels=@($figs|ForEach-Object {$_.value_labels_checked});saved_delta_signs=$signs;report=Join-Path $review 'STATIC_SEMANTICS.json'}|ConvertTo-Json -Depth 6